.TH pginfo 1L "Jan 91" "Homebrewed"name "formatstring"
.SH NAME
pginfo \- get info about a postgres database
.SH SYNOPSIS
.B pginfo
database
.SH DESCRIPTION
pginfo tries to collect some useful information about a given database.
.SH SEE ALSO
spog(1L)
.SH BUGS
Lots, I think.
.SH AUTHORS
Juergen Schoenwaelder (schoenw@ibr.cs.tu-bs.de). 
