.PATH: ${.CURDIR}/tmp
HEADERS+= acl.h align.h c.h daemon.h datum.h fastpath.h fstack.h hasht.h \
	installinfo.h libpq-be.h libpq-fe.h libpq-fs.h libpq.h master.h \
	miscadmin.h nodeFuncs.h portal.h postgres.h pqcomm.h simplelists.h \
	stringinfo.h utilities.h
