#
# $Header$
#

.PATH: ${.CURDIR}/rules/prs2

SRCS+= prs2append.c prs2attr.c prs2bkwd.c prs2define.c prs2delete.c \
	prs2explain.c prs2impexp.c prs2inout.c prs2locks.c prs2main.c \
	prs2plans.c prs2putlocks.c prs2rel.c prs2replace.c prs2retrieve.c \
	prs2stack.c prs2tup.c prs2view.c
