#!/bin/sh
#
# $Header$
#
SEDFILE=/usr/tmp/Makefile.sed.$$
CONFFILE=/usr/tmp/Makefile.config.$$
MOREMAKEFLAGS=""
#
if [ -z "$1" ]; then
	echo "Usage: $0 portname [compiler]"
	exit 1
fi
case $1 in
	aix)
		cat > $SEDFILE << 'EOF'
s/^PORTNAME=.*/PORTNAME=aix/
s/^OLD_CC=.*/OLD_CC=/
s/^AR_TYPE=.*/AR_TYPE=-DUSE_AIA/
s/^NEED_STRINGS=.*/NEED_STRINGS=/
s/^BSD_WAIT3.*=/BSD_WAIT3=-D_BSD/
s/^MORESRCS=.*/MORESRCS=setenv.c/
s/^MOREOBJS=.*/MOREOBJS=setenv.o/
s/^MORELIBS=.*/MORELIBS=-lbsd/
EOF
		;;
	alpha)
		cat > $SEDFILE << 'EOF'
s/^PORTNAME=.*/PORTNAME=alpha/
s/^OLD_CC=.*/OLD_CC=/
s/^AR_TYPE=.*/AR_TYPE=/
s/^NEED_STRINGS=.*/NEED_STRINGS=/
s/^BSD_WAIT3.*=/BSD_WAIT3=-D_BSD/
s/^MORESRCS=.*/MORESRCS=/
s/^MOREOBJS=.*/MOREOBJS=/
s/^MORELIBS=.*/MORELIBS=-lbsd/
EOF
		;;
	hpux)
		cat > $SEDFILE << 'EOF'
s/^PORTNAME=.*/PORTNAME=hpux/
s/^OLD_CC=.*/OLD_CC=-Dconst=/
s/^AR_TYPE=.*/AR_TYPE=-DUSE_RANLIB/
s/^NEED_STRINGS=.*/NEED_STRINGS=/
s/^BSD_WAIT3.*=/BSD_WAIT3=/
s/^MORESRCS=.*/MORESRCS=setenv.c/
s/^MOREOBJS=.*/MOREOBJS=setenv.o/
s/^MORELIBS=.*/MORELIBS=/
EOF
		;;
	linux)
		cat > $SEDFILE << 'EOF'
s/^PORTNAME=.*/PORTNAME=linux/
s/^OLD_CC=.*/OLD_CC=/
s/^AR_TYPE=.*/AR_TYPE=/
s/^NEED_STRINGS=.*/NEED_STRINGS=/
s%^BSD_WAIT3.*=%BSD_WAIT3=-D_BSD_SOURCE -I/usr/include/bsd%
s/^MORESRCS=.*/MORESRCS=/
s/^MOREOBJS=.*/MOREOBJS=/
s/^MORELIBS=.*/MORELIBS=-lbsd/
EOF
		;;
	sparc_solaris)
		if [ -z "$2" ]; then
			CC=cc
		else
			CC=$2
		fi
		echo "$0: using $CC"
		export CC
		case $CC in
		solcc)
			cat > $SEDFILE << 'EOF'
s/^PORTNAME=.*/PORTNAME=sparc_solaris/
s/^OLD_CC=.*/OLD_CC=-BSD -notraditional -Dd_fileno=d_ino/
s/^AR_TYPE=.*/AR_TYPE=/
s/^NEED_STRINGS=.*/NEED_STRINGS=-DNEED_STRINGS/
s/^BSD_WAIT3.*=/BSD_WAIT3=/
s/^MORESRCS=.*/MORESRCS=setenv.c/
s/^MOREOBJS=.*/MOREOBJS=setenv.o/
s/^MORELIBS=.*/MORELIBS=/
EOF
			;;
		cc)
			cat > $SEDFILE << 'EOF'
s/^PORTNAME=.*/PORTNAME=sparc_solaris/
s%^OLD_CC=.*%OLD_CC=-Dd_fileno=d_ino -I/usr/ucbinclude%
s/^AR_TYPE=.*/AR_TYPE=/
s/^NEED_STRINGS=.*/NEED_STRINGS=-DNEED_STRINGS/
s/^BSD_WAIT3.*=/BSD_WAIT3=/
s/^MORESRCS=.*/MORESRCS=setenv.c/
s/^MOREOBJS=.*/MOREOBJS=setenv.o/
s%^MORELIBS=.*%MORELIBS=-R/usr/ucblib -L/usr/ucblib -lucb%
EOF
			;;
		esac
		;;
	sparc)
		cat > $SEDFILE << 'EOF'
s/^PORTNAME=.*/PORTNAME=sparc/
s/^OLD_CC=.*/OLD_CC=-Dvoid="char *" -Dconst=/
s/^AR_TYPE=.*/AR_TYPE=-DUSE_RANLIB/
s/^NEED_STRINGS=.*/NEED_STRINGS=-DNEED_STRINGS/
s/^BSD_WAIT3.*=/BSD_WAIT3=/
s/^MORESRCS=.*/MORESRCS=strerror.c setenv.c/
s/^MOREOBJS=.*/MOREOBJS=strerror.o setenv.o/
s/^MORELIBS=.*/MORELIBS=/
EOF
		;;
	ultrix4)
		cat > $SEDFILE << 'EOF'
s/^PORTNAME=.*/PORTNAME=ultrix4/
s/^OLD_CC=.*/OLD_CC=-Dvoid="char *" -Dconst=/
s/^AR_TYPE=.*/AR_TYPE=-DUSE_RANLIB/
s/^NEED_STRINGS=.*/NEED_STRINGS=/
s/^BSD_WAIT3.*=/BSD_WAIT3=/
s/^MORESRCS=.*/MORESRCS=strdup.c/
s/^MOREOBJS=.*/MOREOBJS=strdup.o/
s/^MORELIBS=.*/MORELIBS=/
EOF
		;;
	*)
		echo "$0: invalid port name:" $1
		echo "$0: valid port names are:"
		echo "$0: aix alpha hpux linux sparc_solaris sparc ultrix4"
		exit 1;
		;;
esac
sed -f $SEDFILE < Makefile.boot > $CONFFILE
make $MOREMAKEFLAGS -f $CONFFILE
rm -f $SEDFILE $CONFFILE
