/* $Header$ */
extern void set_ii_NumKeyAttributes ARGS((IndexInfo node, int value));
extern int get_ii_NumKeyAttributes ARGS((IndexInfo node));
extern void set_ii_KeyAttributeNumbers ARGS((IndexInfo node, AttributeNumberPtr value));
extern AttributeNumberPtr get_ii_KeyAttributeNumbers ARGS((IndexInfo node));
extern void set_ri_RangeTableIndex ARGS((RelationInfo node, Index value));
extern Index get_ri_RangeTableIndex ARGS((RelationInfo node));
extern void set_ri_RelationDesc ARGS((RelationInfo node, Relation value));
extern Relation get_ri_RelationDesc ARGS((RelationInfo node));
extern void set_ri_NumIndices ARGS((RelationInfo node, int value));
extern int get_ri_NumIndices ARGS((RelationInfo node));
extern void set_ri_IndexRelationDescs ARGS((RelationInfo node, RelationPtr value));
extern RelationPtr get_ri_IndexRelationDescs ARGS((RelationInfo node));
extern void set_ri_IndexRelationInfo ARGS((RelationInfo node, IndexInfoPtr value));
extern IndexInfoPtr get_ri_IndexRelationInfo ARGS((RelationInfo node));
extern void set_tc_retrieved ARGS((TupleCount node, int value));
extern int get_tc_retrieved ARGS((TupleCount node));
extern void set_tc_appended ARGS((TupleCount node, int value));
extern int get_tc_appended ARGS((TupleCount node));
extern void set_tc_deleted ARGS((TupleCount node, int value));
extern int get_tc_deleted ARGS((TupleCount node));
extern void set_tc_replaced ARGS((TupleCount node, int value));
extern int get_tc_replaced ARGS((TupleCount node));
extern void set_tc_inserted ARGS((TupleCount node, int value));
extern int get_tc_inserted ARGS((TupleCount node));
extern void set_tc_processed ARGS((TupleCount node, int value));
extern int get_tc_processed ARGS((TupleCount node));
extern void set_es_direction ARGS((EState node, ScanDirection value));
extern ScanDirection get_es_direction ARGS((EState node));
extern void set_es_time ARGS((EState node, abstime value));
extern abstime get_es_time ARGS((EState node));
extern void set_es_owner ARGS((EState node, ObjectId value));
extern ObjectId get_es_owner ARGS((EState node));
extern void set_es_locks ARGS((EState node, List value));
extern List get_es_locks ARGS((EState node));
extern void set_es_subplan_info ARGS((EState node, List value));
extern List get_es_subplan_info ARGS((EState node));
extern void set_es_error_message ARGS((EState node, Name value));
extern Name get_es_error_message ARGS((EState node));
extern void set_es_range_table ARGS((EState node, List value));
extern List get_es_range_table ARGS((EState node));
extern void set_es_qualification_tuple ARGS((EState node, HeapTuple value));
extern HeapTuple get_es_qualification_tuple ARGS((EState node));
extern void set_es_qualification_tuple_id ARGS((EState node, ItemPointer value));
extern ItemPointer get_es_qualification_tuple_id ARGS((EState node));
extern void set_es_relation_relation_descriptor ARGS((EState node, Relation value));
extern void set_es_raw_qualification_tuple ARGS((EState node, HeapTuple value));
extern HeapTuple get_es_raw_qualification_tuple ARGS((EState node));
extern Relation get_es_relation_relation_descriptor ARGS((EState node));
extern void set_es_into_relation_descriptor ARGS((EState node, Relation value));
extern Relation get_es_into_relation_descriptor ARGS((EState node));
extern void set_es_result_relation_info ARGS((EState node, RelationInfo value));
extern RelationInfo get_es_result_relation_info ARGS((EState node));
extern void set_es_tuplecount ARGS((EState node, TupleCount value));
extern TupleCount get_es_tuplecount ARGS((EState node));
extern void set_es_param_list_info ARGS((EState node, ParamListInfo value));
extern ParamListInfo get_es_param_list_info ARGS((EState node));
extern void set_es_prs2_info ARGS((EState node, Prs2EStateInfo value));
extern Prs2EStateInfo get_es_prs2_info ARGS((EState node));
extern void set_es_explain_relation ARGS((EState node, Relation value));
extern Relation get_es_explain_relation ARGS((EState node));
extern void set_es_BaseId ARGS((EState node, int value));
extern int get_es_BaseId ARGS((EState node));
extern void set_ecxt_scantuple ARGS((ExprContext node, List value));
extern List get_ecxt_scantuple ARGS((ExprContext node));
extern void set_ecxt_scantype ARGS((ExprContext node, AttributePtr value));
extern AttributePtr get_ecxt_scantype ARGS((ExprContext node));
extern void set_ecxt_scan_buffer ARGS((ExprContext node, Buffer value));
extern Buffer get_ecxt_scan_buffer ARGS((ExprContext node));
extern void set_ecxt_innertuple ARGS((ExprContext node, List value));
extern List get_ecxt_innertuple ARGS((ExprContext node));
extern void set_ecxt_innertype ARGS((ExprContext node, AttributePtr value));
extern AttributePtr get_ecxt_innertype ARGS((ExprContext node));
extern void set_ecxt_inner_buffer ARGS((ExprContext node, Buffer value));
extern Buffer get_ecxt_inner_buffer ARGS((ExprContext node));
extern void set_ecxt_outertuple ARGS((ExprContext node, List value));
extern List get_ecxt_outertuple ARGS((ExprContext node));
extern void set_ecxt_outertype ARGS((ExprContext node, AttributePtr value));
extern AttributePtr get_ecxt_outertype ARGS((ExprContext node));
extern void set_ecxt_outer_buffer ARGS((ExprContext node, Buffer value));
extern Buffer get_ecxt_outer_buffer ARGS((ExprContext node));
extern void set_ecxt_relation ARGS((ExprContext node, Relation value));
extern Relation get_ecxt_relation ARGS((ExprContext node));
extern void set_ecxt_relid ARGS((ExprContext node, Index value));
extern Index get_ecxt_relid ARGS((ExprContext node));
extern void set_ecxt_param_list_info ARGS((ExprContext node, ParamListInfo value));
extern ParamListInfo get_ecxt_param_list_info ARGS((ExprContext node));
extern void set_hook_pre_procnode ARGS((HookNode node, HookFunction value));
extern HookFunction get_hook_pre_procnode ARGS((HookNode node));
extern void set_hook_pre_endnode ARGS((HookNode node, HookFunction value));
extern HookFunction get_hook_pre_endnode ARGS((HookNode node));
extern void set_hook_post_initnode ARGS((HookNode node, HookFunction value));
extern HookFunction get_hook_post_initnode ARGS((HookNode node));
extern void set_hook_post_procnode ARGS((HookNode node, HookFunction value));
extern HookFunction get_hook_post_procnode ARGS((HookNode node));
extern void set_hook_post_endnode ARGS((HookNode node, HookFunction value));
extern HookFunction get_hook_post_endnode ARGS((HookNode node));
extern void set_hook_data ARGS((HookNode node, Pointer value));
extern Pointer get_hook_data ARGS((HookNode node));
extern void set_base_id ARGS((BaseNode node, int value));
extern int get_base_id ARGS((BaseNode node));
extern void set_base_hook ARGS((BaseNode node, HookNode value));
extern HookNode get_base_hook ARGS((BaseNode node));
extern void set_cs_OuterTuple ARGS((CommonState node, List value));
extern List get_cs_OuterTuple ARGS((CommonState node));
extern void set_cs_TupType ARGS((CommonState node, AttributePtr value));
extern AttributePtr get_cs_TupType ARGS((CommonState node));
extern void set_cs_TupValue ARGS((CommonState node, Pointer value));
extern Pointer get_cs_TupValue ARGS((CommonState node));
extern void set_cs_Level ARGS((CommonState node, int value));
extern int get_cs_Level ARGS((CommonState node));
extern void set_cs_ScanType ARGS((CommonState node, AttributePtr value));
extern AttributePtr get_cs_ScanType ARGS((CommonState node));
extern void set_cs_ScanAttributes ARGS((CommonState node, AttributeNumberPtr value));
extern AttributeNumberPtr get_cs_ScanAttributes ARGS((CommonState node));
extern void set_cs_NumScanAttributes ARGS((CommonState node, int value));
extern int get_cs_NumScanAttributes ARGS((CommonState node));
extern void set_cs_ExprContext ARGS((CommonState node, ExprContext value));
extern ExprContext get_cs_ExprContext ARGS((CommonState node));
extern void set_ex_SatState ARGS((ExistentialState node, List value));
extern List get_ex_SatState ARGS((ExistentialState node));
extern void set_rs_Loop ARGS((ResultState node, int value));
extern int get_rs_Loop ARGS((ResultState node));
extern void set_as_whichplan ARGS((AppendState node, int value));
extern int get_as_whichplan ARGS((AppendState node));
extern void set_as_nplans ARGS((AppendState node, int value));
extern int get_as_nplans ARGS((AppendState node));
extern void set_as_initialized ARGS((AppendState node, ListPtr value));
extern ListPtr get_as_initialized ARGS((AppendState node));
extern void set_as_rtentries ARGS((AppendState node, List value));
extern List get_as_rtentries ARGS((AppendState node));
extern void set_rcs_whichSequence ARGS((RecursiveState node, int value));
extern int get_rcs_whichSequence ARGS((RecursiveState node));
extern void set_rcs_whichPlan ARGS((RecursiveState node, int value));
extern int get_rcs_whichPlan ARGS((RecursiveState node));
extern void set_rcs_numPlans ARGS((RecursiveState node, List value));
extern List get_rcs_numPlans ARGS((RecursiveState node));
extern void set_rcs_initialized ARGS((RecursiveState node, ListPtr value));
extern ListPtr get_rcs_initialized ARGS((RecursiveState node));
extern void set_rcs_rtentries ARGS((RecursiveState node, List value));
extern List get_rcs_rtentries ARGS((RecursiveState node));
extern void set_rcs_effectsNoted ARGS((RecursiveState node, bool value));
extern bool get_rcs_effectsNoted ARGS((RecursiveState node));
extern void set_rcs_tempsSwapped ARGS((RecursiveState node, bool value));
extern bool get_rcs_tempsSwapped ARGS((RecursiveState node));
extern void set_ps_whichplan ARGS((ParallelState node, int value));
extern int get_ps_whichplan ARGS((ParallelState node));
extern void set_ps_nplans ARGS((ParallelState node, int value));
extern int get_ps_nplans ARGS((ParallelState node));
extern void set_ps_initialized ARGS((ParallelState node, ListPtr value));
extern ListPtr get_ps_initialized ARGS((ParallelState node));
extern void set_ps_rtentries ARGS((ParallelState node, List value));
extern List get_ps_rtentries ARGS((ParallelState node));
extern void set_css_currentRelation ARGS((CommonScanState node, Relation value));
extern Relation get_css_currentRelation ARGS((CommonScanState node));
extern void set_css_currentScanDesc ARGS((CommonScanState node, HeapScanDesc value));
extern HeapScanDesc get_css_currentScanDesc ARGS((CommonScanState node));
extern ScanStateRuleInfo get_css_ruleInfo ARGS((CommonScanState node));
extern void set_css_ruleInfo ARGS((CommonScanState node, ScanStateRuleInfo value));
extern void set_ss_ProcOuterFlag ARGS((ScanState node, bool value));
extern bool get_ss_ProcOuterFlag ARGS((ScanState node));
extern void set_ss_OldRelId ARGS((ScanState node, Index value));
extern Index get_ss_OldRelId ARGS((ScanState node));
extern void set_iss_NumIndices ARGS((IndexScanState node, int value));
extern int get_iss_NumIndices ARGS((IndexScanState node));
extern void set_iss_IndexPtr ARGS((IndexScanState node, int value));
extern int get_iss_IndexPtr ARGS((IndexScanState node));
extern void set_iss_ScanKeys ARGS((IndexScanState node, ScanKeyPtr value));
extern ScanKeyPtr get_iss_ScanKeys ARGS((IndexScanState node));
extern void set_iss_NumScanKeys ARGS((IndexScanState node, IntPtr value));
extern IntPtr get_iss_NumScanKeys ARGS((IndexScanState node));
extern void set_iss_RuntimeKeyInfo ARGS((IndexScanState node, Pointer value));
extern Pointer get_iss_RuntimeKeyInfo ARGS((IndexScanState node));
extern void set_iss_RelationDescs ARGS((IndexScanState node, RelationPtr value));
extern RelationPtr get_iss_RelationDescs ARGS((IndexScanState node));
extern void set_iss_ScanDescs ARGS((IndexScanState node, IndexScanDescPtr value));
extern IndexScanDescPtr get_iss_ScanDescs ARGS((IndexScanState node));
extern void set_nl_PortalFlag ARGS((NestLoopState node, bool value));
extern bool get_nl_PortalFlag ARGS((NestLoopState node));
extern void set_mj_OSortopI ARGS((MergeJoinState node, List value));
extern List get_mj_OSortopI ARGS((MergeJoinState node));
extern void set_mj_ISortopO ARGS((MergeJoinState node, List value));
extern List get_mj_ISortopO ARGS((MergeJoinState node));
extern void set_mj_JoinState ARGS((MergeJoinState node, int value));
extern int get_mj_JoinState ARGS((MergeJoinState node));
extern void set_mj_MarkedTuple ARGS((MergeJoinState node, List value));
extern List get_mj_MarkedTuple ARGS((MergeJoinState node));
extern void set_hj_HashTable ARGS((HashJoinState node, HashJoinTable value));
extern HashJoinTable get_hj_HashTable ARGS((HashJoinState node));
extern void set_hj_CurBucket ARGS((HashJoinState node, HashBucket value));
extern HashBucket get_hj_CurBucket ARGS((HashJoinState node));
extern void set_hj_CurTuple ARGS((HashJoinState node, HeapTuple value));
extern HeapTuple get_hj_CurTuple ARGS((HashJoinState node));
extern void set_hj_NBatch ARGS((HashJoinState node, int value));
extern int get_hj_NBatch ARGS((HashJoinState node));
extern void set_hj_OuterBatches ARGS((HashJoinState node, File *value));
extern File *get_hj_OuterBatches ARGS((HashJoinState node));
extern void set_hj_OuterBatchPos ARGS((HashJoinState node, char **value));
extern char **get_hj_OuterBatchPos ARGS((HashJoinState node));
extern void set_hj_InnerBatches ARGS((HashJoinState node, File *value));
extern File *get_hj_InnerBatches ARGS((HashJoinState node));
extern void set_hj_InnerBatchSizes ARGS((HashJoinState node, int *value));
extern int *get_hj_InnerBatchSizes ARGS((HashJoinState node));
extern void set_hj_InnerHashKey ARGS((HashJoinState node, Var value));
extern Var get_hj_InnerHashKey ARGS((HashJoinState node));
extern void set_hj_CurBatch ARGS((HashJoinState node, int value));
extern int get_hj_CurBatch ARGS((HashJoinState node));
extern void set_hj_ReadPos ARGS((HashJoinState node, char *value));
extern char *get_hj_ReadPos ARGS((HashJoinState node));
extern void set_hj_ReadBlk ARGS((HashJoinState node, int value));
extern int get_hj_ReadBlk ARGS((HashJoinState node));
extern void set_mat_Flag ARGS((MaterialState node, bool value));
extern bool get_mat_Flag ARGS((MaterialState node));
extern void set_mat_TempRelation ARGS((MaterialState node, Relation value));
extern Relation get_mat_TempRelation ARGS((MaterialState node));
extern void set_sort_Flag ARGS((SortState node, bool value));
extern bool get_sort_Flag ARGS((SortState node));
extern void set_sort_Keys ARGS((SortState node, Pointer value));
extern Pointer get_sort_Keys ARGS((SortState node));
extern void set_sort_TempRelation ARGS((SortState node, Relation value));
extern Relation get_sort_TempRelation ARGS((SortState node));
extern void set_hashNBatch ARGS((HashState node, int value));
extern int get_hashNBatch ARGS((HashState node));
extern void set_hashBatches ARGS((HashState node, File *value));
extern File *get_hashBatches ARGS((HashState node));
extern void set_hashBatchPos ARGS((HashState node, char **value));
extern char **get_hashBatchPos ARGS((HashState node));
extern void set_hashBatchSizes ARGS((HashState node, int *value));
extern int *get_hashBatchSizes ARGS((HashState node));
extern IndexInfo MakeIndexInfo ARGS((int ii_NumKeyAttributes, AttributeNumberPtr ii_KeyAttributeNumbers));
extern void PrintIndexInfo ARGS((FILE *fp, IndexInfo node));
extern bool EqualIndexInfo ARGS((IndexInfo a, IndexInfo b));
extern RelationInfo MakeRelationInfo ARGS((Index ri_RangeTableIndex, Relation ri_RelationDesc, int ri_NumIndices, RelationPtr ri_IndexRelationDescs, IndexInfoPtr ri_IndexRelationInfo));
extern void PrintRelationInfo ARGS((FILE *fp, RelationInfo node));
extern bool EqualRelationInfo ARGS((RelationInfo a, RelationInfo b));
extern TupleCount MakeTupleCount ARGS((int tc_retrieved, int tc_appended, int tc_deleted, int tc_replaced, int tc_inserted, int tc_processed));
extern void PrintTupleCount ARGS((FILE *fp, TupleCount node));
extern bool EqualTupleCount ARGS((TupleCount a, TupleCount b));
extern EState MakeEState ARGS((ScanDirection es_direction, abstime es_time, ObjectId es_owner, List es_locks, List es_subplan_info, Name es_error_message, List es_range_table, HeapTuple es_qualification_tuple, ItemPointer es_qualification_tuple_id, Relation es_relation_relation_descriptor, Relation es_into_relation_descriptor, RelationInfo es_result_relation_info, TupleCount es_tuplecount, ParamListInfo es_param_list_info, Prs2EStateInfo es_prs2_info, Relation
es_explain_relation, int es_BaseId));
extern void PrintEState ARGS((FILE *fp, EState node));
extern bool EqualEState ARGS((EState a, EState b));
extern ExprContext MakeExprContext ARGS((List ecxt_scantuple, AttributePtr ecxt_scantype, Buffer ecxt_scan_buffer, List ecxt_innertuple, AttributePtr ecxt_innertype, Buffer ecxt_inner_buffer, List ecxt_outertuple, AttributePtr ecxt_outertype, Buffer ecxt_outer_buffer, Relation ecxt_relation, Index ecxt_relid, ParamListInfo ecxt_param_list_info));
extern void PrintExprContext ARGS((FILE *fp, ExprContext node));
extern bool EqualExprContext ARGS((ExprContext a, ExprContext b));
extern HookNode MakeHookNode ARGS((HookFunction hook_pre_procnode, HookFunction hook_pre_endnode, HookFunction hook_post_initnode, HookFunction hook_post_procnode, HookFunction hook_post_endnode, Pointer hook_data));
extern void PrintHookNode ARGS((FILE *fp, HookNode node));
extern bool EqualHookNode ARGS((HookNode a, HookNode b));
extern BaseNode MakeBaseNode ARGS((int base_id, HookNode base_hook));
extern void PrintBaseNode ARGS((FILE *fp, BaseNode node));
extern bool EqualBaseNode ARGS((BaseNode a, BaseNode b));
extern CommonState MakeCommonState ARGS((List cs_OuterTuple, AttributePtr cs_TupType, Pointer cs_TupValue, int cs_Level, AttributePtr cs_ScanType, AttributeNumberPtr cs_ScanAttributes, int cs_NumScanAttributes, ExprContext cs_ExprContext));
extern void PrintCommonState ARGS((FILE *fp, CommonState node));
extern bool EqualCommonState ARGS((CommonState a, CommonState b));
extern ExistentialState MakeExistentialState ARGS((List ex_SatState));
extern void PrintExistentialState ARGS((FILE *fp, ExistentialState node));
extern bool EqualExistentialState ARGS((ExistentialState a, ExistentialState b));
extern ResultState MakeResultState ARGS((int rs_Loop));
extern void PrintResultState ARGS((FILE *fp, ResultState node));
extern bool EqualResultState ARGS((ResultState a, ResultState b));
extern AppendState MakeAppendState ARGS((int as_whichplan, int as_nplans, ListPtr as_initialized, List as_rtentries));
extern void PrintAppendState ARGS((FILE *fp, AppendState node));
extern bool EqualAppendState ARGS((AppendState a, AppendState b));
extern RecursiveState MakeRecursiveState ARGS((int rcs_whichSequence, int rcs_whichPlan, List rcs_numPlans, ListPtr rcs_initialized, List rcs_rtentries, bool rcs_effectsNoted, bool rcs_tempsSwapped));
extern void PrintRecursiveState ARGS((FILE *fp, RecursiveState node));
extern bool EqualRecursiveState ARGS((RecursiveState a, RecursiveState b));
extern ParallelState MakeParallelState ARGS((int ps_whichplan, int ps_nplans, ListPtr ps_initialized, List ps_rtentries));
extern void PrintParallelState ARGS((FILE *fp, ParallelState node));
extern bool EqualParallelState ARGS((ParallelState a, ParallelState b));
extern CommonScanState MakeCommonScanState ARGS((Relation css_currentRelation, HeapScanDesc css_currentScanDesc));
extern void PrintCommonScanState ARGS((FILE *fp, CommonScanState node));
extern bool EqualCommonScanState ARGS((CommonScanState a, CommonScanState b));
extern ScanState MakeScanState ARGS((bool ss_ProcOuterFlag, Index ss_OldRelId));
extern void PrintScanState ARGS((FILE *fp, ScanState node));
extern bool EqualScanState ARGS((ScanState a, ScanState b));
extern IndexScanState MakeIndexScanState ARGS((int iss_NumIndices, int iss_IndexPtr, ScanKeyPtr iss_ScanKeys, IntPtr iss_NumScanKeys, Pointer iss_RuntimeKeyInfo, RelationPtr iss_RelationDescs, IndexScanDescPtr iss_ScanDescs));
extern void PrintIndexScanState ARGS((FILE *fp, IndexScanState node));
extern bool EqualIndexScanState ARGS((IndexScanState a, IndexScanState b));
extern NestLoopState MakeNestLoopState ARGS((bool nl_PortalFlag));
extern void PrintNestLoopState ARGS((FILE *fp, NestLoopState node));
extern bool EqualNestLoopState ARGS((NestLoopState a, NestLoopState b));
extern MergeJoinState MakeMergeJoinState ARGS((List mj_OSortopI, List mj_ISortopO, int mj_JoinState, List mj_MarkedTuple));
extern void PrintMergeJoinState ARGS((FILE *fp, MergeJoinState node));
extern bool EqualMergeJoinState ARGS((MergeJoinState a, MergeJoinState b));
extern HashJoinState MakeHashJoinState ARGS((int mj_OSortopI));
extern void PrintHashJoinState ARGS((FILE *fp, HashJoinState node));
extern bool EqualHashJoinState ARGS((HashJoinState a, HashJoinState b));
extern MaterialState MakeMaterialState ARGS((bool mat_Flag, Relation mat_TempRelation));
extern void PrintMaterialState ARGS((FILE *fp, MaterialState node));
extern bool EqualMaterialState ARGS((MaterialState a, MaterialState b));
extern SortState MakeSortState ARGS((bool sort_Flag, Pointer sort_Keys, Relation sort_TempRelation));
extern void PrintSortState ARGS((FILE *fp, SortState node));
extern bool EqualSortState ARGS((SortState a, SortState b));
extern UniqueState MakeUniqueState ARGS((int sort_Flag));
extern void PrintUniqueState ARGS((FILE *fp, UniqueState node));
extern bool EqualUniqueState ARGS((UniqueState a, UniqueState b));
extern HashState MakeHashState ARGS((int sort_Flag));
extern void PrintHashState ARGS((FILE *fp, HashState node));
extern bool EqualHashState ARGS((HashState a, HashState b));
