extern void set_ri_RangeTableIndex ARGS((RelationInfo node, Index value));
extern Index get_ri_RangeTableIndex ARGS((RelationInfo node));
extern void set_ri_RelationDesc ARGS((RelationInfo node, Relation value));
extern Relation get_ri_RelationDesc ARGS((RelationInfo node));
extern void set_ri_NumIndices ARGS((RelationInfo node, int value));
extern int get_ri_NumIndices ARGS((RelationInfo node));
extern void set_ri_IndexRelationDescs ARGS((RelationInfo node, RelationPtr value));
extern RelationPtr get_ri_IndexRelationDescs ARGS((RelationInfo node));
extern void set_es_direction ARGS((EState node, ScanDirection value));
extern ScanDirection get_es_direction ARGS((EState node));
extern void set_es_time ARGS((EState node, abstime value));
extern abstime get_es_time ARGS((EState node));
extern void set_es_owner ARGS((EState node, ObjectId value));
extern ObjectId get_es_owner ARGS((EState node));
extern void set_es_locks ARGS((EState node, List value));
extern List get_es_locks ARGS((EState node));
extern void set_es_subplan_info ARGS((EState node, List value));
extern List get_es_subplan_info ARGS((EState node));
extern void set_es_error_message ARGS((EState node, Name value));
extern Name get_es_error_message ARGS((EState node));
extern void set_es_range_table ARGS((EState node, List value));
extern List get_es_range_table ARGS((EState node));
extern void set_es_qualification_tuple ARGS((EState node, HeapTuple value));
extern HeapTuple get_es_qualification_tuple ARGS((EState node));
extern void set_es_qualification_tuple_id ARGS((EState node, ItemPointer value));
extern ItemPointer get_es_qualification_tuple_id ARGS((EState node));
extern void set_es_relation_relation_descriptor ARGS((EState node, Relation value));
extern Relation get_es_relation_relation_descriptor ARGS((EState node));
extern void set_es_into_relation_descriptor ARGS((EState node, Relation value));
extern Relation get_es_into_relation_descriptor ARGS((EState node));
extern void set_es_result_relation_info ARGS((EState node, RelationInfo value));
extern RelationInfo get_es_result_relation_info ARGS((EState node));
extern void set_sn_OuterTuple ARGS((StateNode node, List value));
extern List get_sn_OuterTuple ARGS((StateNode node));
extern void set_sn_TupType ARGS((StateNode node, AttributePtr value));
extern AttributePtr get_sn_TupType ARGS((StateNode node));
extern void set_sn_TupValue ARGS((StateNode node, Pointer value));
extern Pointer get_sn_TupValue ARGS((StateNode node));
extern void set_sn_Level ARGS((StateNode node, int value));
extern int get_sn_Level ARGS((StateNode node));
extern void set_sn_ScanType ARGS((StateNode node, AttributePtr value));
extern AttributePtr get_sn_ScanType ARGS((StateNode node));
extern void set_rs_Loop ARGS((ResultState node, int value));
extern int get_rs_Loop ARGS((ResultState node));
extern void set_as_whichplan ARGS((AppendState node, int value));
extern int get_as_whichplan ARGS((AppendState node));
extern void set_as_nplans ARGS((AppendState node, int value));
extern int get_as_nplans ARGS((AppendState node));
extern void set_as_initialized ARGS((AppendState node, ListPtr value));
extern ListPtr get_as_initialized ARGS((AppendState node));
extern void set_as_rtentries ARGS((AppendState node, List value));
extern List get_as_rtentries ARGS((AppendState node));
extern void set_cs_PortalFlag ARGS((CommonState node, bool value));
extern bool get_cs_PortalFlag ARGS((CommonState node));
extern void set_cs_currentRelation ARGS((CommonState node, Relation value));
extern Relation get_cs_currentRelation ARGS((CommonState node));
extern void set_cs_currentScanDesc ARGS((CommonState node, HeapScanDesc value));
extern HeapScanDesc get_cs_currentScanDesc ARGS((CommonState node));
extern void set_ss_RuleFlag ARGS((ScanState node, bool value));
extern bool get_ss_RuleFlag ARGS((ScanState node));
extern void set_ss_RuleDesc ARGS((ScanState node, List value));
extern List get_ss_RuleDesc ARGS((ScanState node));
extern void set_ss_ProcLeftFlag ARGS((ScanState node, bool value));
extern bool get_ss_ProcLeftFlag ARGS((ScanState node));
extern void set_ss_OldRelId ARGS((ScanState node, Index value));
extern Index get_ss_OldRelId ARGS((ScanState node));
extern void set_iss_NumIndices ARGS((IndexScanState node, int value));
extern int get_iss_NumIndices ARGS((IndexScanState node));
extern void set_iss_IndexPtr ARGS((IndexScanState node, int value));
extern int get_iss_IndexPtr ARGS((IndexScanState node));
extern void set_iss_ScanKeys ARGS((IndexScanState node, ScanKeyPtr value));
extern ScanKeyPtr get_iss_ScanKeys ARGS((IndexScanState node));
extern void set_iss_NumScanKeys ARGS((IndexScanState node, IntPtr value));
extern IntPtr get_iss_NumScanKeys ARGS((IndexScanState node));
extern void set_iss_RelationDescs ARGS((IndexScanState node, RelationPtr value));
extern RelationPtr get_iss_RelationDescs ARGS((IndexScanState node));
extern void set_iss_ScanDescs ARGS((IndexScanState node, IndexScanDescPtr value));
extern IndexScanDescPtr get_iss_ScanDescs ARGS((IndexScanState node));
extern void set_mj_OSortopI ARGS((MergeJoinState node, List value));
extern List get_mj_OSortopI ARGS((MergeJoinState node));
extern void set_mj_ISortopO ARGS((MergeJoinState node, List value));
extern List get_mj_ISortopO ARGS((MergeJoinState node));
extern void set_mj_MarkFlag ARGS((MergeJoinState node, bool value));
extern bool get_mj_MarkFlag ARGS((MergeJoinState node));
extern void set_mj_FrwdMarkPos ARGS((MergeJoinState node, List value));
extern List get_mj_FrwdMarkPos ARGS((MergeJoinState node));
extern void set_mj_BkwdMarkPos ARGS((MergeJoinState node, List value));
extern List get_mj_BkwdMarkPos ARGS((MergeJoinState node));
extern void set_sort_Flag ARGS((SortState node, bool value));
extern bool get_sort_Flag ARGS((SortState node));
extern void set_sort_Keys ARGS((SortState node, List value));
extern List get_sort_Keys ARGS((SortState node));
extern void set_ex_SatState ARGS((ExistentialState node, List value));
extern List get_ex_SatState ARGS((ExistentialState node));
extern RelationInfo MakeRelationInfo ARGS((Index ri_RangeTableIndex, Relation ri_RelationDesc, int ri_NumIndices, RelationPtr ri_IndexRelationDescs));
extern void PrintRelationInfo ARGS((RelationInfo node));
extern bool EqualRelationInfo ARGS((RelationInfo a, RelationInfo b));
extern EState MakeEState ARGS((ScanDirection es_direction, abstime es_time, ObjectId es_owner, List es_locks, List es_subplan_info, Name es_error_message, List es_range_table, HeapTuple es_qualification_tuple, ItemPointer es_qualification_tuple_id, Relation es_relation_relation_descriptor, Relation es_into_relation_descriptor, RelationInfo es_result_relation_info));
extern void PrintEState ARGS((EState node));
extern bool EqualEState ARGS((EState a, EState b));
extern StateNode MakeStateNode ARGS((List sn_OuterTuple, AttributePtr sn_TupType, Pointer sn_TupValue, int sn_Level, AttributePtr sn_ScanType));
extern void PrintStateNode ARGS((StateNode node));
extern bool EqualStateNode ARGS((StateNode a, StateNode b));
extern ResultState MakeResultState ARGS((int rs_Loop));
extern void PrintResultState ARGS((ResultState node));
extern bool EqualResultState ARGS((ResultState a, ResultState b));
extern AppendState MakeAppendState ARGS((int as_whichplan, int as_nplans, ListPtr as_initialized, List as_rtentries));
extern void PrintAppendState ARGS((AppendState node));
extern bool EqualAppendState ARGS((AppendState a, AppendState b));
extern CommonState MakeCommonState ARGS((bool cs_PortalFlag, Relation cs_currentRelation, HeapScanDesc cs_currentScanDesc));
extern void PrintCommonState ARGS((CommonState node));
extern bool EqualCommonState ARGS((CommonState a, CommonState b));
extern ScanState MakeScanState ARGS((bool ss_RuleFlag, List ss_RuleDesc, bool ss_ProcLeftFlag, Index ss_OldRelId));
extern void PrintScanState ARGS((ScanState node));
extern bool EqualScanState ARGS((ScanState a, ScanState b));
extern IndexScanState MakeIndexScanState ARGS((int iss_NumIndices, int iss_IndexPtr, ScanKeyPtr iss_ScanKeys, IntPtr iss_NumScanKeys, RelationPtr iss_RelationDescs, IndexScanDescPtr iss_ScanDescs));
extern void PrintIndexScanState ARGS((IndexScanState node));
extern bool EqualIndexScanState ARGS((IndexScanState a, IndexScanState b));
extern NestLoopState MakeNestLoopState ARGS((int iss_NumIndices));
extern void PrintNestLoopState ARGS((NestLoopState node));
extern bool EqualNestLoopState ARGS((NestLoopState a, NestLoopState b));
extern MergeJoinState MakeMergeJoinState ARGS((List mj_OSortopI, List mj_ISortopO, bool mj_MarkFlag, List mj_FrwdMarkPos, List mj_BkwdMarkPos));
extern void PrintMergeJoinState ARGS((MergeJoinState node));
extern bool EqualMergeJoinState ARGS((MergeJoinState a, MergeJoinState b));
extern SortState MakeSortState ARGS((bool sort_Flag, List sort_Keys));
extern void PrintSortState ARGS((SortState node));
extern bool EqualSortState ARGS((SortState a, SortState b));
extern ExistentialState MakeExistentialState ARGS((List ex_SatState));
extern void PrintExistentialState ARGS((ExistentialState node));
extern bool EqualExistentialState ARGS((ExistentialState a, ExistentialState b));
