/* $Header$ */
extern BaseNode ExecGetPrivateState ARGS((Plan node));
extern void ExecAssignNodeBaseInfo ARGS((EState estate, BaseNode basenode, Plan parent));
extern void ExecAssignDebugHooks ARGS((BaseNode base node, int basenode));
extern void ExecAssignExprContext ARGS((EState estate, CommonState commonstate));
extern Attribute ExecGetTypeInfo ARGS((Relation relDesc));
extern AttributePtr ExecMakeTypeInfo ARGS((int nelts));
extern void ExecSetTypeInfo ARGS((int index, struct attribute **typeInfo, int typeID, int attNum, int attLen, char *attName, Boolean attbyVal));
extern void ExecFreeTypeInfo ARGS((struct attribute **typeInfo));
extern Pointer ExecMakeSkeys ARGS((int noSkeys));
extern void ExecSetSkeys ARGS((int index, struct skey skeys[], int attNo, int opr, DATUM value));
extern void ExecSetSkeysValue ARGS((int index, struct skey skeys[], DATUM value));
extern void ExecFreeSkeys ARGS((struct skey skeys[]));
extern Pointer ExecMakeTLValues ARGS((int noDomains));
extern void ExecSetTLValues ARGS((int index, Pointer TLValues, Datum value));
extern void ExecFreeTLValues ARGS((Pointer TLValues));
extern Plan get_innerPlan ARGS((Plan node));
extern Plan get_outerPlan ARGS((Plan node));
extern List QueryDescGetTypeInfo ARGS((List queryDesc));
extern List ExecCollect ARGS((List l, int applyFunction, int collectFunction, List applyParameters));
extern List ExecUniqueCons ARGS((List list1, List list2));
extern List ExecGetVarAttlistFromExpr ARGS((Node expr, List relationNum));
extern List ExecGetVarAttlistFromTLE ARGS((List tle, List relationNum));
extern AttributeNumberPtr ExecMakeAttsFromList ARGS((List attlist, int *numAttsPtr));
extern void ExecInitScanAttributes ARGS((Plan node));
extern AttributeNumberPtr ExecMakeBogusScanAttributes ARGS((int natts));
extern void ExecFreeScanAttributes ARGS((AttributeNumberPtr ptr));
extern Pointer FQdGetCommand ARGS((List queryDesc));
extern Pointer FQdGetCount ARGS((List queryDesc));
extern Pointer FGetOperation ARGS((List queryDesc));
extern Pointer FQdGetParseTree ARGS((List queryDesc));
extern Pointer FQdGetPlan ARGS((List queryDesc));
extern Pointer FQdGetState ARGS((List queryDesc));
extern Pointer FQdGetFeature ARGS((List queryDesc));
extern Pointer Fparse_tree_range_table ARGS((List queryDesc));
extern Pointer Fparse_tree_result_relation ARGS((List queryDesc));
extern void say_at_init ARGS(());
extern void say_pre_proc ARGS(());
extern void say_pre_end ARGS(());
extern void say_post_init ARGS(());
extern void say_post_proc ARGS(());
extern void say_post_end ARGS(());
extern void say_yow ARGS(());
extern void noop ARGS(());
extern void InitHook ARGS((HookNode hook));
extern void NoisyHook ARGS((HookNode hook));
extern String GetNodeName ARGS((Node node));
extern Plan AddMaterialNode ARGS((Plan plan));
extern Plan AddSortNode ARGS((Plan plan, int op));
extern Plan AddUniqueNode ARGS((Plan plan));
