/*     
 *      FILE
 *     	storeplan
 *     
 *      DESCRIPTION
 *     	Routines to store and retrieve plans
 *
 *      IDENTIFICATION
 *      $Header$
 *     
 */
#include "c.h"
#include "postgres.h"
#include "pg_lisp.h"
#include "nodes.h"
#include "params.h"

/*-------------------------------------------------
 *
 * StringToPlan
 *     given a string (generated by "PlanToString")
 *     reconstruct the plan (or any (?) other LispValue
 *     structure).
 */
LispValue
StringToPlan (string)
	char *string;
{
	extern LispValue lispReadString();
	return(lispReadString(string));

}

 
/*-------------------------------------------------
 *
 * StringToPlanWithParams
 *     Same as StringToPlan, but it also returns
 *     an array (of type ParamListInfo) of all the Param
 *     nodes
 */
LispValue
StringToPlanWithParams (string, paramListP)
	char *string;
	ParamListInfo * paramListP;
{
	extern LispValue lispReadStringWithParams();
	return(lispReadStringWithParams(string, paramListP));

}

 
