PG_INCLUDE=../backend

all: int4_abs.o circle.o

int4_abs.o: int4_abs.c
	cc -c -g -PIC -I$(PG_INCLUDE) int4_abs.c

circle.o: circle.c
	cc -c -g -PIC -I$(PG_INCLUDE) circle.c

int4_abs.so: int4_abs.o
	ld -dc -dp -Bdynamic -o int4_abs.so int4_abs.o

circle.so: circle.o
	ld -dc -dp -Bdynamic -o circle.so circle.o
