#
# Build and install postgres.
#
# You have to cd into doc/ and ref/ by hand to make them.  They are
# not done automatically because they depend on groff, which you may not
# have installed.
# Formatted copies of the documents are already made in ../{doc,ref}
# for you.
#

SUBDIR= backend libpq bin regress

.include <postgres.subdir.mk>
