.PATH: ${.CURDIR}/utils/adt

#
# DEAD CODE: a copy of smgr.c was found here.  live version: storage/smgr/...
#

SRCS+= acl.c arrayfuncs.c bool.c char.c date.c datum.c dt.c filename.c float.c ftype.c geo-ops.c geo-selfuncs.c int.c lo_regprocs.c misc.c nabstime.c name.c not_in.c numutils.c oid.c oidchar16.c oidint4.c regexp.c regproc.c selfuncs.c tid.c tim.c varlena.c
