extern LispValue lambda1 ARGS((LispValue qual));
extern LispValue pull_constant_clauses ARGS((LispValue quals));
extern LispValue lambda2 ARGS((LispValue qual));
extern LispValue pull_relation_level_clauses ARGS((LispValue quals));
extern LispValue clause_relids_vars ARGS((LispValue clause));
extern LispValue clause_relids ARGS((LispValue clause));
extern LispValue nested_clause_p ARGS((LispValue clause));
extern bool relation_level_clause_p ARGS((LispValue clause));
extern LispValue contains_not ARGS((LispValue clause));
extern LispValue join_clause_p ARGS((LispValue clause));
extern LispValue qual_clause_p ARGS((LispValue clause));
extern LispValue lambda3 ARGS((LispValue arg));
extern bool function_index_clause_p ARGS((LispValue clause, LispValue rel, LispValue index));
extern void *fix_opid ARGS((LispValue clause));
extern LispValue fix_opids ARGS((LispValue clauses));
extern LispValue get_relattval ARGS((LispValue clause));
extern LispValue get_relsatts ARGS((LispValue clause));
