extern LispValue new_level_tlist ARGS((LispValue tlist, LispValue prevtlist, LispValue prevlevel));
extern LispValue new_level_qual ARGS((LispValue quals, LispValue prevtlist, LispValue prevlevel));
extern LispValue replace_clause_nestvar_refs ARGS((LispValue clause, LispValue prevtlist, LispValue prevlevel));
extern LispValue replace_subclause_nestvar_refs ARGS((LispValue clauses, LispValue prevtlist, LispValue prevlevel));
extern LispValue replace_nestvar_refs ARGS((LispValue var, LispValue prevtlist, LispValue prevlevel));
extern LispValue new_result_tlist ARGS((LispValue tlist, LispValue ltlist, LispValue rtlist, LispValue levelnum, LispValue sorted));
extern LispValue new_result_qual ARGS((LispValue clauses, LispValue ltlist, LispValue rtlist, LispValue levelnum));
extern LispValue replace_clause_resultvar_refs ARGS((LispValue clause, LispValue ltlist, LispValue rtlist, LispValue levelnum));
extern LispValue replace_subclause_resultvar_refs ARGS((LispValue clauses, LispValue ltlist, LispValue rtlist, LispValue levelnum));
extern LispValue replace_resultvar_refs ARGS((LispValue var, LispValue ltlist, LispValue rtlist, LispValue levelnum));
extern void *set_tlist_references ARGS((LispValue plan));
extern void *set_join_tlist_references ARGS((LispValue join));
extern void *set_tempscan_tlist_references ARGS((LispValue tempscan));
extern void *set_temp_tlist_references ARGS((LispValue temp));
extern LispValue join_references ARGS((LispValue clauses, LispValue outer_tlist, LispValue inner_tlist));
extern LispValue index_outerjoin_references ARGS((LispValue inner_indxqual, LispValue outer_tlist, LispValue inner_relid));
extern LispValue replace_clause_joinvar_refs ARGS((LispValue clause, LispValue outer_tlist, LispValue inner_tlist));
extern LispValue replace_subclause_joinvar_refs ARGS((LispValue clauses, LispValue outer_tlist, LispValue inner_tlist));
extern LispValue replace_joinvar_refs ARGS((LispValue var, LispValue outer_tlist, LispValue inner_tlist));
extern LispValue tlist_temp_references ARGS((LispValue tempid, LispValue tlist));
