BINDIR=	/usr/local/bin
LIBDIR=	/usr/local/lib
#
# Normally MACHINE gets set by a parent Makefile.global, but if the
# tools subtree is detached to bootstrap, we'll dummy it up here.
# Nothing here really needs it.
#
MACHINE?= unknown
